Fix header width and remove line break from sub-title
ebi-ait/projects-index pull request #47
Opened 2021-06-02 15:50 UTC by ke4

Changes:
- Fix the maximum width of the header box
- Remove the line break from the sub-title

2021-06-02 15:57 UTC, jacobwindsor approved these changes

2021-06-02 16:02 UTC, MightyAx submitted a review, later dismissed

2021-06-02 16:21 UTC, ke4 commented on src/app/components/global-header/global-header.component.html
> +<section class="vf-hero vf-hero--800 | vf-u-fullbleed vf-hero-hca" style="background-color: #3355aa">
oh, good spot. We don't need that. That was my 1st try and I accidentally committed it. Sorry. I am going to remove that

2021-06-02 16:30 UTC, ke4 commented on src/app/components/global-header/global-header.component.css
> +}
this is a property change inside `vf-hero__content` class

2021-06-03 08:50 UTC, MightyAx submitted a review, later dismissed
Glad my review was useful!

2021-06-03 08:52 UTC, jacobwindsor approved these changes

2021-06-04 14:54 UTC, jacobwindsor requested changes

2021-06-04 14:54 UTC, jacobwindsor commented on src/app/components/global-header/global-header.component.ts
> +        return 'HCA Project Catalogue';
You don't need the else here

2021-06-04 14:54 UTC, jacobwindsor commented on src/app/components/global-header/global-header.component.ts
> +      return 'A comprehensive list of cellular resolution datasets for the Human Cell Atlas.';
No else here either

2021-06-04 15:16 UTC, jacobwindsor approved these changes

2021-06-07 08:11 UTC, MightyAx submitted a review, later dismissed

2021-06-07 09:52 UTC, jacobwindsor approved these changes

2021-06-07 11:11 UTC, MightyAx approved these changes

2021-06-07 13:54 UTC, merged