Pretty error messages
ebi-ait/projects-index pull request #48
Opened 2021-06-03 11:01 UTC by jacobwindsor

- Adds an error module
- Redirects all global JS errors to general error page
- Redirects 404s to 404 page
- Redirects 500s to 500 page
- Redirects all other HTTP failures to general error page

2021-06-03 13:51 UTC, MightyAx submitted a review, later dismissed
Minor edits to open and closing tags, but if there's a good reason it's fine.

2021-06-03 14:24 UTC, jacobwindsor commented on src/app/components/global-header/global-header.component.html
> +        >Human Cell Atlas Project Catalogue</a
This is the formatting done by prettier. I agree with the second one - this looks weird. You can't change the formatting done by prettier and in general I like the style. Maybe we should investigate using ESLint instead but for another ticket?

2021-06-03 14:38 UTC, sandykadam commented
@jacobwindsor Since you created custom error pages, you might want to add in conf file as well, so Nginx will redirect to respective error for e.g

```
error_page   500 502 503 504  /humancellatlas/project-catalogue/error;
```

https://github.com/ebi-ait/projects-index/blob/master/docker-assets/default.conf#L12

https://github.com/ebi-ait/projects-index/blob/master/docker-assets/default.conf#L16

Check in local first with Docker build.

2021-06-07 11:39 UTC, jacobwindsor commented
@sandykadam I have done that now! thanks for the suggestion

2021-06-07 11:52 UTC, amnonkhen commented on src/app/components/global-header/global-header.component.html
> +        >Human Cell Atlas Project Catalogue</a
Maybe the [jsx brackets](https://prettier.io/docs/en/options.html#jsx-brackets) could help?

2021-06-07 11:54 UTC, amnonkhen commented on docker-assets/default.conf
> +    error_page  500              /humancellatlas/project-catalogue/error/500;
Why do we differentiate between 500 & 50x errors?

2021-06-07 12:03 UTC, amnonkhen approved these changes

2021-06-07 12:04 UTC, amnonkhen requested changes
Looks well.
I agree with @MightyAx's comments about closing bracket location.

2021-06-07 12:08 UTC, ke4 submitted a review, later dismissed
I agree with @amnonkhen and @MightyAx 's findings (formatting issues), but other than those it looks fine to me 👍 💯

2021-06-07 12:31 UTC, jacobwindsor commented
@amnonkhen I don't know where your comment about 500 pages has gone but it is because the VF [500 page](https://stable.visual-framework.dev//patterns/error-pages/index.html?q=error#500) has an error specifically for 500

2021-06-07 12:51 UTC, jacobwindsor reviewed
The issue with HTML formatting is being actively worked on in this [PR](https://github.com/prettier/prettier/issues/5377#issuecomment-678644985). So, I don't think we can do anything about this now

2021-06-07 12:55 UTC, amnonkhen commented
@jacobwindsor Do you mean that prettier cannot currently put the bracket at the end of the previous line? I will approve for now, but we should sort this out soon. Another code formatter might be a good idea here.

2021-06-07 12:55 UTC, amnonkhen submitted a review, later dismissed

2021-06-07 15:49 UTC, ke4 approved these changes

2021-06-08 09:10 UTC, amnonkhen approved these changes

2021-06-21 13:37 UTC, jacobwindsor commented
Merging now but there is still work to be done for this in [this card](https://app.zenhub.com/workspaces/dcp-ingest-product-development-5f71ca62a3cb47326bdc1b5c/issues/ebi-ait/dcp-ingest-central/334)

2021-06-21 13:42 UTC, ke4 approved these changes

2021-06-21 23:26 UTC, amnonkhen approved these changes

2021-06-22 07:40 UTC, merged