Make pagination respond to changing page better
ebi-ait/projects-index pull request #62
Opened 2021-06-23 16:58 UTC by jacobwindsor

- Fixes issues in #58 
  - First and last page links not shown when on first or last page
  - UI fixes for changing the layout depending on the page

2021-06-24 10:29 UTC, MightyAx approved these changes
This is so much better in use now.
I've removed a `console.log` that I presume was checked in accidentally.

2021-06-24 10:29 UTC, MightyAx commented on src/app/projects/components/pagination/pagination.component.ts
> +    console.log(pageNumber);
should probably remove this.

2021-06-24 10:53 UTC, aaclan-ebi approved these changes
very noice!!!

2021-06-24 10:57 UTC, aaclan-ebi commented
hold on, i think there's a bug when there's only 1 page

![Screenshot 2021-06-24 at 11 56 11](https://user-images.githubusercontent.com/31281398/123251612-50037280-d4e3-11eb-9610-105caf3532c8.png)

2021-06-24 10:58 UTC, aaclan-ebi commented
![Screenshot 2021-06-24 at 11 58 20](https://user-images.githubusercontent.com/31281398/123251781-7e814d80-d4e3-11eb-9748-17ea103444e0.png)

2021-06-24 13:08 UTC, MightyAx requested changes
please fix bug for displaying less than 2 pages of results...
perhaps just hide the paginator?

2021-06-24 15:00 UTC, MightyAx commented on src/app/projects/components/pagination/pagination.component.html
> +<nav class="vf-pagination" aria-label="Pagination" *ngIf="totalPages <= 1">
shouldn't this be:
```
*ngIf="totalPages > 1"
```

2021-06-24 15:02 UTC, jacobwindsor commented on src/app/projects/components/pagination/pagination.component.html
> +<nav class="vf-pagination" aria-label="Pagination" *ngIf="totalPages <= 1">
Wow brain not working...

2021-06-24 16:22 UTC, aaclan-ebi approved these changes

2021-06-25 08:17 UTC, MightyAx approved these changes

2021-06-25 08:35 UTC, merged